"""Static dataset of popular Dominican Republic beaches for the tourism map UI.

Pure-Python so the dashboard runs fully offline (no DB or API required).
Each beach is a dict with a consistent schema; see BEACH_FIELDS for the keys.

Coordinates and descriptive details are compiled from the DR Ministry of
Tourism guides, national-park data, and travel references. Treat minor
amenity/fee notes as local observations that can change.
"""
from __future__ import annotations

BEACH_FIELDS = (
    "name",
    "province",
    "region",
    "latitude",
    "longitude",
    "access_type",
    "access_description",
    "entrance_fee",
    "parking",
    "beach_type",
    "activities",
    "wildlife",
    "ecosystem",
    "protected_area",
    "facilities",
    "water_conditions",
    "best_time_to_visit",
    "description",
)


def google_maps_url(lat: float, lon: float) -> str:
    """Return a Google Maps pin link for the given coordinates."""
    return f"https://www.google.com/maps/search/?api=1&query={lat},{lon}"


# Region groupings used for map colouring and filtering.
REGION_EAST = "East (Punta Cana / La Romana)"
REGION_NORTH = "North (Puerto Plata / Cabarete)"
REGION_SAMANA = "Samaná Peninsula"
REGION_SOUTH = "South (Santo Domingo / South Coast)"
REGION_SOUTHWEST = "Southwest (Barahona / Pedernales)"

REGION_COLORS = {
    REGION_EAST: "#1f77b4",       # blue
    REGION_NORTH: "#2ca02c",      # green
    REGION_SAMANA: "#9467bd",     # purple
    REGION_SOUTH: "#ff7f0e",      # orange
    REGION_SOUTHWEST: "#d62728",  # red
}


BEACHES: list[dict] = [
    # ----------------------------------------------------------------- East
    {
        "name": "Playa Bávaro",
        "province": "La Altagracia",
        "region": REGION_EAST,
        "latitude": 18.6661,
        "longitude": -68.3968,
        "access_type": "Public",
        "access_description": "Public beach access points between resorts off the main Punta Cana highway.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Family", "Resort", "Swimming"],
        "activities": ["Swimming", "Parasailing", "Catamaran Tours", "Snorkeling", "Diving"],
        "wildlife": ["Pelicans", "Reef Fish", "Sea Stars"],
        "ecosystem": "Coral reef and coconut coastline",
        "protected_area": False,
        "facilities": ["Restrooms", "Showers", "Restaurants", "Beach Clubs", "Lifeguards (resort sections)"],
        "water_conditions": "Calm, turquoise; occasional rip currents",
        "best_time_to_visit": "December–April (dry, calm season)",
        "description": "Classic palm-lined white-sand beach on the Coconut Coast with full resort amenities and abundant water sports.",
    },
    {
        "name": "Playa Macao",
        "province": "La Altagracia",
        "region": REGION_EAST,
        "latitude": 18.8065,
        "longitude": -68.5710,
        "access_type": "Public",
        "access_description": "Paved local road ~20–30 min from Bávaro; small parking lot.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Surfing", "Local", "Wild"],
        "activities": ["Surfing", "Swimming", "Photography"],
        "wildlife": ["Frigatebirds", "Shorebirds"],
        "ecosystem": "Open Atlantic beach with coral-rock cliffs",
        "protected_area": False,
        "facilities": ["Palapa Restaurants", "Surf Schools"],
        "water_conditions": "Strong surf and currents; heed warning flags",
        "best_time_to_visit": "October–April (best surf)",
        "description": "Wild, undeveloped golden-sand beach famed for surfing; minimal formal amenities, so come prepared.",
    },
    {
        "name": "Playa Juanillo",
        "province": "La Altagracia",
        "region": REGION_EAST,
        "latitude": 18.5000,
        "longitude": -68.3730,
        "access_type": "Controlled",
        "access_description": "Inside gated Cap Cana; public lot near Tortuga Bay restaurant.",
        "entrance_fee": "Free (resort area)",
        "parking": True,
        "beach_type": ["Resort", "Upscale", "Swimming"],
        "activities": ["Snorkeling", "Paddleboarding", "Kayaking", "Beach Volleyball", "Kiteboarding"],
        "wildlife": ["Reef Fish", "Sea Birds"],
        "ecosystem": "Protected Caribbean shoreline",
        "protected_area": False,
        "facilities": ["Beach Club", "Restaurants", "Sunlounger Rentals", "Security"],
        "water_conditions": "Generally calm with steady onshore wind",
        "best_time_to_visit": "November–March (dry season)",
        "description": "Upscale pristine white-sand beach within Cap Cana, often ranked among the country's finest.",
    },
    {
        "name": "Playa Blanca",
        "province": "La Altagracia",
        "region": REGION_EAST,
        "latitude": 18.5674,
        "longitude": -68.3635,
        "access_type": "Controlled",
        "access_description": "Within Cap Cana marina area; reachable by car or resort transfer.",
        "entrance_fee": "Varies",
        "parking": True,
        "beach_type": ["Resort", "Swimming"],
        "activities": ["Kitesurfing", "Swimming", "Beach Clubs"],
        "wildlife": ["Tropical Fish", "Pelicans"],
        "ecosystem": "Sheltered Caribbean cove",
        "protected_area": False,
        "facilities": ["Beach Club", "Restaurant"],
        "water_conditions": "Calm and shallow",
        "best_time_to_visit": "November–March (dry season)",
        "description": "Crescent cove by Cap Cana marina with a popular beach club and calm swimming water.",
    },
    {
        "name": "Bayahibe Beach",
        "province": "La Romana",
        "region": REGION_EAST,
        "latitude": 18.3746,
        "longitude": -68.8412,
        "access_type": "Public",
        "access_description": "Easy highway access from La Romana; public parking, small park fee.",
        "entrance_fee": "Small park fee",
        "parking": True,
        "beach_type": ["Local", "Diving", "Swimming"],
        "activities": ["Scuba Diving", "Boat Excursions", "Snorkeling"],
        "wildlife": ["Sea Turtles", "Nurse Sharks", "Coral Fish"],
        "ecosystem": "Cotubanamá National Park (Parque Nacional del Este)",
        "protected_area": True,
        "facilities": ["Restaurants", "Dive Centers", "Boat Docks"],
        "water_conditions": "Clear and calm",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Laid-back fishing village beach and the gateway for boat trips to Saona and Catalina islands.",
    },
    {
        "name": "Dominicus Beach",
        "province": "La Romana",
        "region": REGION_EAST,
        "latitude": 18.3493,
        "longitude": -68.8330,
        "access_type": "Public",
        "access_description": "Easy highway access near Bayahibe; resort-lined with public access.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Resort", "Family", "Swimming"],
        "activities": ["Swimming", "Diving", "Snorkeling"],
        "wildlife": ["Coral Fish", "Sea Turtles"],
        "ecosystem": "Cotubanamá National Park (Blue Flag)",
        "protected_area": True,
        "facilities": ["Restrooms", "Chairs", "Food Stands", "Resorts"],
        "water_conditions": "Clear, sandy, calm",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Blue Flag–certified developed beach next to Bayahibe with soft sand and offshore reefs.",
    },
    {
        "name": "Canto de la Playa (Saona)",
        "province": "La Romana",
        "region": REGION_EAST,
        "latitude": 18.1272,
        "longitude": -68.6934,
        "access_type": "Boat",
        "access_description": "Boat trip from Bayahibe; landings only at authorised zones.",
        "entrance_fee": "Included in tours",
        "parking": False,
        "beach_type": ["Island", "Wild", "Swimming"],
        "activities": ["Snorkeling", "Photography", "Swimming"],
        "wildlife": ["Starfish", "Sea Turtles", "Coral Fish"],
        "ecosystem": "Cotubanamá National Park (Isla Saona)",
        "protected_area": True,
        "facilities": ["Tour Vendors (no permanent facilities)"],
        "water_conditions": "Powdery sand, shallow turquoise tidal pools",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Powder-sand beach on protected Isla Saona, circled by vibrant coral reef and natural starfish pools.",
    },
    # ---------------------------------------------------------------- North
    {
        "name": "Playa Dorada",
        "province": "Puerto Plata",
        "region": REGION_NORTH,
        "latitude": 19.7906,
        "longitude": -70.6875,
        "access_type": "Public",
        "access_description": "Adjacent to Puerto Plata city; parking behind Riviera Azul plaza.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Resort", "Family", "Swimming"],
        "activities": ["Swimming", "Golf", "Catamaran Tours", "Water Sports"],
        "wildlife": ["Tropical Fish"],
        "ecosystem": "Developed resort shoreline",
        "protected_area": False,
        "facilities": ["Beach Clubs", "Bars", "Showers", "Boardwalks", "Lifeguards (peak season)"],
        "water_conditions": "Shallow and usually calm",
        "best_time_to_visit": "December–April (dry season)",
        "description": "A 1.9 km golden-sand beach fronting Puerto Plata's first resort cluster, family-friendly and lively.",
    },
    {
        "name": "Playa Sosúa",
        "province": "Puerto Plata",
        "region": REGION_NORTH,
        "latitude": 19.7541,
        "longitude": -70.5180,
        "access_type": "Public",
        "access_description": "Route 5 through Sosúa town; some paid parking along the bay.",
        "entrance_fee": "Free (paid parking)",
        "parking": True,
        "beach_type": ["Local", "Snorkeling", "Swimming"],
        "activities": ["Snorkeling", "Scuba Diving"],
        "wildlife": ["Parrotfish", "Angelfish", "Spotted Drumfish"],
        "ecosystem": "Horseshoe bay protected by coral reef",
        "protected_area": False,
        "facilities": ["Restaurants", "Bars", "Dive Centers", "Changing Areas"],
        "water_conditions": "Shallow near shore; deeper at the reef",
        "best_time_to_visit": "April–September (clearest water)",
        "description": "Horseshoe bay famous for easy snorkeling over a fringing reef plus a lively beachfront scene.",
    },
    {
        "name": "Playa Encuentro",
        "province": "Puerto Plata",
        "region": REGION_NORTH,
        "latitude": 19.7707,
        "longitude": -70.4433,
        "access_type": "Public",
        "access_description": "Turnoff from the coastal highway ~10 km west of Sosúa; roadside parking.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Surfing", "Wild"],
        "activities": ["Surfing", "Surf Lessons"],
        "wildlife": ["Coastal Birds"],
        "ecosystem": "Reef-break surf beach",
        "protected_area": False,
        "facilities": ["Surf Schools", "Outdoor Shower"],
        "water_conditions": "Multiple reef and point breaks; rip currents",
        "best_time_to_visit": "October–April (consistent swell)",
        "description": "The DR's premier surf beach with at least six breaks for all levels and several on-site surf camps.",
    },
    {
        "name": "Cabarete Beach",
        "province": "Puerto Plata",
        "region": REGION_NORTH,
        "latitude": 19.7512,
        "longitude": -70.4087,
        "access_type": "Public",
        "access_description": "~20 min from Puerto Plata airport; free parking, town-front access.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Wind Sports", "Town", "Swimming"],
        "activities": ["Kitesurfing", "Windsurfing", "Foiling", "Paddleboarding"],
        "wildlife": ["Sea Birds", "Reef Fish"],
        "ecosystem": "Wind-exposed bay behind a protective reef",
        "protected_area": False,
        "facilities": ["Restaurants", "Hotels", "Shops", "Rental Schools", "Lifeguards (main beach)"],
        "water_conditions": "Shallow inside the reef; steady trade winds",
        "best_time_to_visit": "June–August & December–February (peak wind)",
        "description": "The 'Water Sports Capital' with 250–300 windy days a year, ideal for kite- and windsurfing.",
    },
    {
        "name": "Punta Rucia",
        "province": "Puerto Plata",
        "region": REGION_NORTH,
        "latitude": 19.9090,
        "longitude": -71.1860,
        "access_type": "Public",
        "access_description": "Rural road on the northwest coast; boat departures for Cayo Arena.",
        "entrance_fee": "Free (tours extra)",
        "parking": True,
        "beach_type": ["Local", "Snorkeling"],
        "activities": ["Snorkeling", "Boat Tours"],
        "wildlife": ["Starfish", "Coral Fish", "Sea Turtles"],
        "ecosystem": "Gateway to Cayo Arena / Montecristi reefs",
        "protected_area": False,
        "facilities": ["Local Restaurants", "Boat Operators"],
        "water_conditions": "Calm and clear",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Quiet fishing-village beach and launch point for the postcard sandbar of Cayo Arena (Paraíso).",
    },
    {
        "name": "La Ensenada",
        "province": "Puerto Plata",
        "region": REGION_NORTH,
        "latitude": 19.8942,
        "longitude": -71.1840,
        "access_type": "Public",
        "access_description": "Near Punta Rucia on the northwest coast; local road access.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Family", "Local", "Swimming"],
        "activities": ["Swimming", "Family Recreation"],
        "wildlife": ["Pelicans", "Reef Fish"],
        "ecosystem": "Sheltered shallow bay",
        "protected_area": False,
        "facilities": ["Local Food Stands", "Picnic Areas"],
        "water_conditions": "Very shallow and calm",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Family-friendly local beach with shallow, calm water — popular with Dominican weekenders.",
    },
    {
        "name": "Playa Grande",
        "province": "María Trinidad Sánchez",
        "region": REGION_NORTH,
        "latitude": 19.6405,
        "longitude": -70.1578,
        "access_type": "Public",
        "access_description": "Off the coastal highway near Río San Juan; on-site parking.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Surfing", "Swimming", "Scenic"],
        "activities": ["Surfing", "Swimming", "Photography"],
        "wildlife": ["Sea Birds", "Fish"],
        "ecosystem": "Atlantic coastal ecosystem with cliffs",
        "protected_area": False,
        "facilities": ["Restaurants", "Sunlounger Rentals"],
        "water_conditions": "Open Atlantic with surf; watch currents",
        "best_time_to_visit": "October–April (best surf)",
        "description": "Long, dramatic golden-sand beach backed by cliffs and greenery; strong surf in winter months.",
    },
    {
        "name": "Playa Caletón",
        "province": "María Trinidad Sánchez",
        "region": REGION_NORTH,
        "latitude": 19.6392,
        "longitude": -70.1714,
        "access_type": "Public",
        "access_description": "Small cove near Playa Grande and Río San Juan; short walk in.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Local", "Snorkeling", "Swimming"],
        "activities": ["Snorkeling", "Swimming"],
        "wildlife": ["Coral Fish", "Sea Urchins"],
        "ecosystem": "Protected pocket cove",
        "protected_area": False,
        "facilities": ["Local Food Vendors"],
        "water_conditions": "Calm, clear, shallow",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Tiny turquoise 'Playita Caletón' cove beloved by locals for calm snorkeling and weekend gatherings.",
    },
    # --------------------------------------------------------------- Samaná
    {
        "name": "Playa Rincón",
        "province": "Samaná",
        "region": REGION_SAMANA,
        "latitude": 19.2895,
        "longitude": -69.2499,
        "access_type": "Road or Boat",
        "access_description": "15-min dirt road from Las Galeras, or a short local boat ride.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Wild", "Scenic", "Swimming"],
        "activities": ["Swimming", "Snorkeling", "Horseback Riding", "Photography", "Birdwatching"],
        "wildlife": ["Brown Pelicans", "Crabs", "Reef Fish", "Hawksbill Turtles"],
        "ecosystem": "Palm forest and river estuary near Los Haitises",
        "protected_area": False,
        "facilities": ["Palapa Restaurants", "Outhouses", "Picnic Tables"],
        "water_conditions": "Unusually calm reef-guarded bay",
        "best_time_to_visit": "December–April (dry season)",
        "description": "A ~5 km undeveloped paradise of palm-backed white sand, regularly ranked among the world's best beaches.",
    },
    {
        "name": "Playa Frontón",
        "province": "Samaná",
        "region": REGION_SAMANA,
        "latitude": 19.2860,
        "longitude": -69.1880,
        "access_type": "Boat or Hiking Trail",
        "access_description": "Boat from Las Galeras or a rugged jungle hike.",
        "entrance_fee": "Free (boat extra)",
        "parking": False,
        "beach_type": ["Wild", "Snorkeling", "Remote"],
        "activities": ["Snorkeling", "Freediving", "Cliff Photography"],
        "wildlife": ["Parrotfish", "Sea Fans", "Coral Species"],
        "ecosystem": "Coral reef beneath limestone cliffs (Los Haitises zone)",
        "protected_area": True,
        "facilities": ["None (bring supplies)"],
        "water_conditions": "Clear with the DR's best shore snorkeling",
        "best_time_to_visit": "December–April (calm seas)",
        "description": "Remote cliff-backed beach with arguably the best snorkeling reef on the Samaná peninsula.",
    },
    {
        "name": "Playa Madama",
        "province": "Samaná",
        "region": REGION_SAMANA,
        "latitude": 19.2890,
        "longitude": -69.1990,
        "access_type": "Boat or Hiking Trail",
        "access_description": "Short hike or boat from Las Galeras.",
        "entrance_fee": "Free",
        "parking": False,
        "beach_type": ["Wild", "Remote", "Snorkeling"],
        "activities": ["Snorkeling", "Exploring Caves"],
        "wildlife": ["Coral Fish", "Marine Invertebrates"],
        "ecosystem": "Sheltered cove framed by cliffs and caves",
        "protected_area": True,
        "facilities": ["None (bring supplies)"],
        "water_conditions": "Calm and sheltered",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Small secluded cove flanked by dramatic cliffs and sea caves, reached on foot or by boat.",
    },
    {
        "name": "Playa Bonita",
        "province": "Samaná",
        "region": REGION_SAMANA,
        "latitude": 19.3076,
        "longitude": -69.5698,
        "access_type": "Public",
        "access_description": "Paved road from Las Terrenas; roadside and hotel parking.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Surfing", "Swimming", "Scenic"],
        "activities": ["Swimming", "Surfing", "Beach Restaurants"],
        "wildlife": ["Pelicans", "Tropical Fish"],
        "ecosystem": "Open palm-lined Atlantic beach",
        "protected_area": False,
        "facilities": ["Boutique Hotels", "Restaurants"],
        "water_conditions": "Moderate surf; good for beginners",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Relaxed palm-fringed beach near Las Terrenas with boutique hotels and gentle surf.",
    },
    {
        "name": "Playa Cosón",
        "province": "Samaná",
        "region": REGION_SAMANA,
        "latitude": 19.3044,
        "longitude": -69.5818,
        "access_type": "Public",
        "access_description": "Coastal road west of Las Terrenas; ample open parking.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Scenic", "Swimming", "Long"],
        "activities": ["Swimming", "Jogging", "Photography"],
        "wildlife": ["Migratory Birds", "Fish"],
        "ecosystem": "Wide open Atlantic beach",
        "protected_area": False,
        "facilities": ["Beachfront Seafood Restaurants"],
        "water_conditions": "Open water, gentle waves",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Long, broad sweep of golden sand famed for sunset seafood shacks and space to roam.",
    },
    {
        "name": "Playa Las Ballenas",
        "province": "Samaná",
        "region": REGION_SAMANA,
        "latitude": 19.3137,
        "longitude": -69.5454,
        "access_type": "Public",
        "access_description": "Walkable from Las Terrenas town centre.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Town", "Swimming", "Family"],
        "activities": ["Kayaking", "Paddleboarding", "Swimming"],
        "wildlife": ["Sea Turtles", "Reef Fish"],
        "ecosystem": "Town beach facing three small 'whale' islets",
        "protected_area": False,
        "facilities": ["Restaurants", "Bars", "Rentals"],
        "water_conditions": "Calm and shallow",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Las Terrenas town beach named for the offshore islets, with calm water and easy rentals.",
    },
    {
        "name": "Cayo Levantado",
        "province": "Samaná",
        "region": REGION_SAMANA,
        "latitude": 19.1715,
        "longitude": -69.2482,
        "access_type": "Boat",
        "access_description": "Boat from Samaná town or hotel docks; dock fee usually included.",
        "entrance_fee": "Dock fee (often included in tours)",
        "parking": False,
        "beach_type": ["Island", "Family", "Swimming"],
        "activities": ["Snorkeling", "Swimming", "Whale Watching", "Kayaking"],
        "wildlife": ["Humpback Whales", "Pelicans", "Reef Fish"],
        "ecosystem": "Reef-fringed island in Samaná Bay",
        "protected_area": True,
        "facilities": ["Restaurants", "Restrooms", "Chair Rentals", "Nature Path"],
        "water_conditions": "Soft sand, clear shallow water",
        "best_time_to_visit": "January–March (whale season)",
        "description": "The palm-fringed 'Bacardi Island' with postcard sand, snorkeling reefs, and winter whale tours.",
    },
    # ---------------------------------------------------------------- South
    {
        "name": "Boca Chica Beach",
        "province": "Santo Domingo",
        "region": REGION_SOUTH,
        "latitude": 18.4510,
        "longitude": -69.6090,
        "access_type": "Public",
        "access_description": "~30 km east of Santo Domingo via Highway DR-3; shared vans available.",
        "entrance_fee": "Free (paid parking)",
        "parking": True,
        "beach_type": ["Urban", "Family", "Swimming"],
        "activities": ["Swimming", "Family Recreation", "Snorkeling", "Boat Tours"],
        "wildlife": ["Mangrove Birds", "Reef Fish"],
        "ecosystem": "Reef-protected lagoon with mangrove patches",
        "protected_area": False,
        "facilities": ["Cabañas", "Restaurants", "Changing Rooms", "Restrooms"],
        "water_conditions": "Very calm and shallow lagoon",
        "best_time_to_visit": "December–April (dry season)",
        "description": "The capital's classic urban beach: a breakwater reef forms a shallow lagoon perfect for families.",
    },
    {
        "name": "Playa Juan Dolio",
        "province": "San Pedro de Macorís",
        "region": REGION_SOUTH,
        "latitude": 18.4458,
        "longitude": -69.4136,
        "access_type": "Public",
        "access_description": "Coastal highway east of Boca Chica; motoconcho or car.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Resort", "Family", "Swimming"],
        "activities": ["Swimming", "Jet Ski", "Diving", "Restaurants"],
        "wildlife": ["Pelicans", "Fish"],
        "ecosystem": "Sandy shore near the Catalina reef",
        "protected_area": False,
        "facilities": ["Restaurants", "Snack Stands", "Shops"],
        "water_conditions": "Shallow; some erosion-narrowed sections",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Wide resort-lined beach near scuba sites; convenient day trip from Santo Domingo.",
    },
    {
        "name": "Playa Guayacanes",
        "province": "San Pedro de Macorís",
        "region": REGION_SOUTH,
        "latitude": 18.4200,
        "longitude": -69.4680,
        "access_type": "Public",
        "access_description": "Coastal road beside Juan Dolio; local parking.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Local", "Family", "Swimming"],
        "activities": ["Swimming", "Fishing", "Photography"],
        "wildlife": ["Coastal Birds"],
        "ecosystem": "Natural sandy shoreline",
        "protected_area": False,
        "facilities": ["Local Seafood Restaurants"],
        "water_conditions": "Shallow; some rocky patches (water shoes)",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Low-key local beach next to Juan Dolio with fishing boats and authentic seafood shacks.",
    },
    # ------------------------------------------------------------ Southwest
    {
        "name": "Bahía de las Águilas",
        "province": "Pedernales",
        "region": REGION_SOUTHWEST,
        "latitude": 17.8408,
        "longitude": -71.6305,
        "access_type": "Boat or 4x4",
        "access_description": "Pedernales → Cabo Rojo/La Cueva, then boat or rough 4x4 the final 6–8 km.",
        "entrance_fee": "Park permit via tour operators",
        "parking": False,
        "beach_type": ["Wild", "Remote", "Scenic"],
        "activities": ["Snorkeling", "Ecotourism", "Hiking", "Photography"],
        "wildlife": ["Hawksbill Sea Turtle", "Green Sea Turtle", "American Flamingo", "Brown Pelican", "Rhinoceros Iguana"],
        "ecosystem": "Jaragua National Park (UNESCO Biosphere Reserve)",
        "protected_area": True,
        "facilities": ["None (carry all food, water, fuel)"],
        "water_conditions": "Exceptionally clear over healthy reefs",
        "best_time_to_visit": "December–April (avoid Jun–Nov storms)",
        "description": "The DR's most untouched beach: ~7 km of virgin white sand in a strictly protected park.",
    },
    {
        "name": "Cabo Rojo",
        "province": "Pedernales",
        "region": REGION_SOUTHWEST,
        "latitude": 17.9287,
        "longitude": -71.6446,
        "access_type": "Road",
        "access_description": "Paved/industrial road south of Pedernales; staging point for Bahía de las Águilas.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Remote", "Scenic", "Swimming"],
        "activities": ["Swimming", "Photography", "Ecotourism"],
        "wildlife": ["Flamingos", "Sea Birds"],
        "ecosystem": "Jaragua National Park coastline",
        "protected_area": True,
        "facilities": ["Boat Operators", "Limited Vendors"],
        "water_conditions": "Calm and clear",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Quiet reddish-sand bay and the main launch point for boats to Bahía de las Águilas.",
    },
    {
        "name": "Playa Blanca (Pedernales)",
        "province": "Pedernales",
        "region": REGION_SOUTHWEST,
        "latitude": 17.9524,
        "longitude": -71.7485,
        "access_type": "Road or Boat",
        "access_description": "Remote far-southwest coast near the Haitian border; guide recommended.",
        "entrance_fee": "Free",
        "parking": False,
        "beach_type": ["Wild", "Remote", "Swimming"],
        "activities": ["Swimming", "Relaxation"],
        "wildlife": ["Pelicans", "Marine Fish"],
        "ecosystem": "Remote arid coastline",
        "protected_area": False,
        "facilities": ["None (bring supplies)"],
        "water_conditions": "Calm and clear",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Isolated white-sand beach on the country's far southwestern tip for true off-grid relaxation.",
    },
    # ------------------------------------------------------- East (expansion)
    {
        "name": "Playa El Cortecito",
        "province": "La Altagracia",
        "region": REGION_EAST,
        "latitude": 18.6880,
        "longitude": -68.4220,
        "access_type": "Public",
        "access_description": "Public fishing-village access in the heart of Bávaro.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Local", "Family", "Swimming"],
        "activities": ["Swimming", "Boating", "Snorkeling"],
        "wildlife": ["Pelicans", "Reef Fish"],
        "ecosystem": "Coconut-coast reef shoreline",
        "protected_area": False,
        "facilities": ["Restaurants", "Souvenir Market", "Boat Vendors"],
        "water_conditions": "Calm and shallow",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Lively fishing-village beach in Bávaro with public access, seafood shacks, and a local market.",
    },
    {
        "name": "Playa Cabeza de Toro",
        "province": "La Altagracia",
        "region": REGION_EAST,
        "latitude": 18.6380,
        "longitude": -68.4180,
        "access_type": "Public",
        "access_description": "Quiet stretch between Punta Cana and Bávaro; local road access.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Quiet", "Swimming"],
        "activities": ["Swimming", "Kitesurfing", "Snorkeling"],
        "wildlife": ["Reef Fish", "Sea Birds"],
        "ecosystem": "Reef-lined coast with nearby lagoons",
        "protected_area": False,
        "facilities": ["Resorts", "Restaurants"],
        "water_conditions": "Calm with steady breeze",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Calmer, less-crowded beach between the big resort zones, popular for kitesurfing.",
    },
    {
        "name": "Playa Uvero Alto",
        "province": "La Altagracia",
        "region": REGION_EAST,
        "latitude": 18.8700,
        "longitude": -68.6540,
        "access_type": "Public",
        "access_description": "North of Macao, ~45 min from Punta Cana; resort road access.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Resort", "Wild", "Swimming"],
        "activities": ["Swimming", "Surfing", "Horseback Riding"],
        "wildlife": ["Shorebirds", "Reef Fish"],
        "ecosystem": "Wide Atlantic beach backed by coconut groves",
        "protected_area": False,
        "facilities": ["Resorts", "Restaurants"],
        "water_conditions": "Moderate surf and breeze",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Long, scenic beach in a quieter northern resort enclave with a wilder feel than Bávaro.",
    },
    {
        "name": "Playa Bibijagua",
        "province": "La Altagracia",
        "region": REGION_EAST,
        "latitude": 18.5210,
        "longitude": -68.3700,
        "access_type": "Public",
        "access_description": "Public beach near Punta Cana village, popular with locals.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Local", "Family", "Swimming"],
        "activities": ["Swimming", "Beach Volleyball", "Photography"],
        "wildlife": ["Pelicans", "Reef Fish"],
        "ecosystem": "Reef-protected white-sand shore",
        "protected_area": False,
        "facilities": ["Local Restaurants", "Picnic Areas"],
        "water_conditions": "Calm and shallow",
        "best_time_to_visit": "December–April (dry season)",
        "description": "A favourite local public beach near Punta Cana, lively on weekends with Dominican families.",
    },
    {
        "name": "Playa Minitas",
        "province": "La Romana",
        "region": REGION_EAST,
        "latitude": 18.4090,
        "longitude": -68.9100,
        "access_type": "Controlled",
        "access_description": "Within Casa de Campo resort; day passes may be required.",
        "entrance_fee": "Resort access",
        "parking": True,
        "beach_type": ["Resort", "Family", "Swimming"],
        "activities": ["Swimming", "Kayaking", "Paddleboarding"],
        "wildlife": ["Reef Fish", "Sea Birds"],
        "ecosystem": "Sheltered man-made cove",
        "protected_area": False,
        "facilities": ["Beach Club", "Restaurant", "Water Sports"],
        "water_conditions": "Very calm, protected",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Manicured crescent beach inside Casa de Campo with calm water and full resort service.",
    },
    {
        "name": "Isla Catalina Beach",
        "province": "La Romana",
        "region": REGION_EAST,
        "latitude": 18.3530,
        "longitude": -68.9970,
        "access_type": "Boat",
        "access_description": "Boat from La Romana / Bayahibe; cruise-line and dive day trips.",
        "entrance_fee": "Included in tours",
        "parking": False,
        "beach_type": ["Island", "Diving", "Swimming"],
        "activities": ["Scuba Diving", "Snorkeling", "Swimming"],
        "wildlife": ["Coral Species", "Reef Fish", "Sea Turtles"],
        "ecosystem": "Cotubanamá National Park reef island",
        "protected_area": True,
        "facilities": ["Tour Vendors (limited)"],
        "water_conditions": "Crystal-clear over coral walls",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Protected reef island off La Romana renowned for 'The Wall' dive site and powder sand.",
    },
    {
        "name": "Playa Mano Juan (Saona)",
        "province": "La Altagracia",
        "region": REGION_EAST,
        "latitude": 18.1400,
        "longitude": -68.7300,
        "access_type": "Boat",
        "access_description": "Boat to Saona's only village; part of national-park tours.",
        "entrance_fee": "Included in tours",
        "parking": False,
        "beach_type": ["Island", "Local", "Wild"],
        "activities": ["Snorkeling", "Swimming", "Photography"],
        "wildlife": ["Sea Turtles", "Reef Fish", "Iguanas"],
        "ecosystem": "Cotubanamá National Park fishing village",
        "protected_area": True,
        "facilities": ["Small Local Eateries", "Turtle Sanctuary"],
        "water_conditions": "Calm, shallow, turquoise",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Saona Island's colourful fishing hamlet with a community sea-turtle conservation project.",
    },
    # ------------------------------------------------------ North (expansion)
    {
        "name": "Playa Cofresí",
        "province": "Puerto Plata",
        "region": REGION_NORTH,
        "latitude": 19.7760,
        "longitude": -70.7600,
        "access_type": "Public",
        "access_description": "West of Puerto Plata city; road access, public entry.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Family", "Resort", "Swimming"],
        "activities": ["Swimming", "Snorkeling", "Photography"],
        "wildlife": ["Reef Fish", "Pelicans"],
        "ecosystem": "Reef-fringed cove",
        "protected_area": False,
        "facilities": ["Restaurants", "Resorts", "Ocean World nearby"],
        "water_conditions": "Calm with some surf at the edges",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Cove beach near Ocean World Adventure Park, with calm swimming and sunset views.",
    },
    {
        "name": "Playa Costambar",
        "province": "Puerto Plata",
        "region": REGION_NORTH,
        "latitude": 19.7850,
        "longitude": -70.7300,
        "access_type": "Public",
        "access_description": "Residential beach community just west of Puerto Plata.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Family", "Quiet", "Swimming"],
        "activities": ["Swimming", "Jogging", "Photography"],
        "wildlife": ["Pelicans", "Reef Fish"],
        "ecosystem": "Calm shallow shoreline",
        "protected_area": False,
        "facilities": ["Local Restaurants", "Bars"],
        "water_conditions": "Calm and shallow",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Easygoing expat-favoured beach with gentle water and a laid-back village feel.",
    },
    {
        "name": "Playa Alicia",
        "province": "Puerto Plata",
        "region": REGION_NORTH,
        "latitude": 19.7600,
        "longitude": -70.5150,
        "access_type": "Public",
        "access_description": "Sosúa; stairway access from the cliff boardwalk.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Quiet", "Swimming", "Scenic"],
        "activities": ["Swimming", "Snorkeling", "Photography"],
        "wildlife": ["Reef Fish", "Sea Birds"],
        "ecosystem": "Cliff-backed white-sand cove",
        "protected_area": False,
        "facilities": ["Boardwalk", "Nearby Restaurants"],
        "water_conditions": "Calm and clear",
        "best_time_to_visit": "April–September (clearest water)",
        "description": "Quieter white-sand alternative to Sosúa's main bay, reached via a scenic cliff boardwalk.",
    },
    {
        "name": "Playa Cambiaso",
        "province": "Puerto Plata",
        "region": REGION_NORTH,
        "latitude": 19.8300,
        "longitude": -70.4500,
        "access_type": "4x4 or Boat",
        "access_description": "Remote beach east of Puerto Plata; rough track or boat.",
        "entrance_fee": "Free",
        "parking": False,
        "beach_type": ["Wild", "Remote", "Eco"],
        "activities": ["Swimming", "Birdwatching", "Ecotourism"],
        "wildlife": ["Mangrove Birds", "Crabs", "Reef Fish"],
        "ecosystem": "River-mouth mangroves and dunes",
        "protected_area": False,
        "facilities": ["None (bring supplies)"],
        "water_conditions": "Calm where the river meets the sea",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Secluded mangrove-backed beach reached by 4x4 or boat, great for nature lovers.",
    },
    {
        "name": "Playa Maimón",
        "province": "Puerto Plata",
        "region": REGION_NORTH,
        "latitude": 19.6700,
        "longitude": -70.0500,
        "access_type": "Public",
        "access_description": "Near Maimón village west of the Amber Cove cruise port.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Local", "Diving", "Swimming"],
        "activities": ["Snorkeling", "Scuba Diving", "Swimming"],
        "wildlife": ["Coral Species", "Reef Fish"],
        "ecosystem": "Bay with offshore coral reef",
        "protected_area": False,
        "facilities": ["Local Restaurants", "Dive Operators"],
        "water_conditions": "Calm bay water",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Local bay beach near Amber Cove with accessible reefs popular for beginner diving.",
    },
    {
        "name": "Kite Beach",
        "province": "Puerto Plata",
        "region": REGION_NORTH,
        "latitude": 19.7560,
        "longitude": -70.4250,
        "access_type": "Public",
        "access_description": "Immediately west of Cabarete Bay; roadside access.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Wind Sports", "Swimming"],
        "activities": ["Kitesurfing", "Windsurfing", "Foiling"],
        "wildlife": ["Sea Birds"],
        "ecosystem": "Flat-water leeward kite zone",
        "protected_area": False,
        "facilities": ["Kite Schools", "Beach Bars"],
        "water_conditions": "Flat inside, waves outside the reef",
        "best_time_to_visit": "June–August (peak wind)",
        "description": "World-famous kiteboarding cove beside Cabarete with flat water and a wave zone offshore.",
    },
    {
        "name": "Playa Sosúa Bay (Charamicos)",
        "province": "Puerto Plata",
        "region": REGION_NORTH,
        "latitude": 19.7560,
        "longitude": -70.5230,
        "access_type": "Public",
        "access_description": "West end of Sosúa bay via Charamicos neighbourhood.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Local", "Snorkeling", "Swimming"],
        "activities": ["Snorkeling", "Swimming", "Boating"],
        "wildlife": ["Parrotfish", "Angelfish"],
        "ecosystem": "Sheltered reef bay",
        "protected_area": False,
        "facilities": ["Restaurants", "Boat Tours"],
        "water_conditions": "Calm, reef-protected",
        "best_time_to_visit": "April–September (clearest water)",
        "description": "The local-side entrance to Sosúa Bay with calm reef water and budget boat-tour operators.",
    },
    # ------------------------------------------- María Trinidad Sánchez / Nagua
    {
        "name": "Playa Diamante",
        "province": "María Trinidad Sánchez",
        "region": REGION_NORTH,
        "latitude": 19.5500,
        "longitude": -69.9300,
        "access_type": "Public",
        "access_description": "Near Cabrera; short track to a sheltered lagoon beach.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Quiet", "Family", "Swimming"],
        "activities": ["Swimming", "Paddleboarding", "Photography"],
        "wildlife": ["Sea Birds", "Reef Fish"],
        "ecosystem": "Crescent lagoon sheltered by a sandbar",
        "protected_area": False,
        "facilities": ["Limited Local Vendors"],
        "water_conditions": "Very calm lagoon",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Hidden crescent lagoon near Cabrera with calm, shallow water ideal for families.",
    },
    {
        "name": "Playa El Bretón",
        "province": "María Trinidad Sánchez",
        "region": REGION_NORTH,
        "latitude": 19.6300,
        "longitude": -69.9700,
        "access_type": "Public",
        "access_description": "Within Cabo Francés Viejo reserve near Cabrera.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Wild", "Scenic", "Eco"],
        "activities": ["Swimming", "Hiking", "Photography"],
        "wildlife": ["Sea Birds", "Crabs"],
        "ecosystem": "Cabo Francés Viejo Scientific Reserve",
        "protected_area": True,
        "facilities": ["None (bring supplies)"],
        "water_conditions": "Open Atlantic; watch currents",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Cliff-backed wild beach inside a coastal scientific reserve with dramatic scenery.",
    },
    # --------------------------------------------------- Samaná (expansion)
    {
        "name": "Playa Las Galeras",
        "province": "Samaná",
        "region": REGION_SAMANA,
        "latitude": 19.3010,
        "longitude": -69.1620,
        "access_type": "Public",
        "access_description": "At the end of the road on the Samaná peninsula tip.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Local", "Family", "Swimming"],
        "activities": ["Swimming", "Snorkeling", "Boating"],
        "wildlife": ["Reef Fish", "Pelicans"],
        "ecosystem": "Calm bay and fishing-village shore",
        "protected_area": False,
        "facilities": ["Restaurants", "Boat Operators", "Dive Shops"],
        "water_conditions": "Calm and shallow",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Relaxed fishing-village beach and the launch point for boats to Rincón and Frontón.",
    },
    {
        "name": "Playa El Valle",
        "province": "Samaná",
        "region": REGION_SAMANA,
        "latitude": 19.3120,
        "longitude": -69.3030,
        "access_type": "Road or Boat",
        "access_description": "Winding mountain road north of Samaná town, or by boat.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Wild", "Scenic", "Remote"],
        "activities": ["Swimming", "Horseback Riding", "Photography"],
        "wildlife": ["Sea Birds", "Crabs"],
        "ecosystem": "River-mouth beach framed by green cliffs",
        "protected_area": False,
        "facilities": ["A Few Local Eateries"],
        "water_conditions": "Surf and currents; swim with care",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Dramatic, little-visited beach where green mountains meet the Atlantic near Samaná.",
    },
    {
        "name": "Playa Punta Popy",
        "province": "Samaná",
        "region": REGION_SAMANA,
        "latitude": 19.3200,
        "longitude": -69.5400,
        "access_type": "Public",
        "access_description": "Along the Las Terrenas seafront boulevard.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Wind Sports", "Town", "Swimming"],
        "activities": ["Kitesurfing", "Swimming", "Paddleboarding"],
        "wildlife": ["Sea Birds", "Reef Fish"],
        "ecosystem": "Breezy town beach",
        "protected_area": False,
        "facilities": ["Restaurants", "Bars", "Kite Schools"],
        "water_conditions": "Breezy with light chop",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Las Terrenas' lively town beach, a local hub for kitesurfing and sunset drinks.",
    },
    # ---------------------------------------- South / South-central (expansion)
    {
        "name": "Playa Najayo",
        "province": "San Cristóbal",
        "region": REGION_SOUTH,
        "latitude": 18.2700,
        "longitude": -70.1600,
        "access_type": "Public",
        "access_description": "West of Santo Domingo near San Cristóbal; road access.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Local", "Family", "Swimming"],
        "activities": ["Swimming", "Fishing", "Photography"],
        "wildlife": ["Pelicans", "Coastal Birds"],
        "ecosystem": "Mixed sand-and-pebble southern shore",
        "protected_area": False,
        "facilities": ["Seafood Restaurants", "Cabañas"],
        "water_conditions": "Moderate waves; some rocky areas",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Popular weekend beach for Santo Domingo locals, lined with open-air seafood eateries.",
    },
    {
        "name": "Playa Palenque",
        "province": "San Cristóbal",
        "region": REGION_SOUTH,
        "latitude": 18.2300,
        "longitude": -70.1500,
        "access_type": "Public",
        "access_description": "Near Nigua/Palenque, southwest of Santo Domingo.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Local", "Swimming"],
        "activities": ["Swimming", "Fishing"],
        "wildlife": ["Coastal Birds"],
        "ecosystem": "Open south-coast beach",
        "protected_area": False,
        "facilities": ["Local Food Stands"],
        "water_conditions": "Moderate Caribbean waves",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Down-to-earth local beach southwest of the capital, busy with Dominican day-trippers.",
    },
    {
        "name": "Playa Palmar de Ocoa",
        "province": "Azua",
        "region": REGION_SOUTH,
        "latitude": 18.1300,
        "longitude": -70.6500,
        "access_type": "Public",
        "access_description": "Bay of Ocoa, off the Sánchez highway in Azua.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Quiet", "Family", "Swimming"],
        "activities": ["Swimming", "Fishing", "Boating"],
        "wildlife": ["Pelicans", "Fish"],
        "ecosystem": "Sheltered bay with calm water",
        "protected_area": False,
        "facilities": ["Vacation Villas", "Local Restaurants"],
        "water_conditions": "Calm bay water",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Tranquil bay beach in Azua known for sport fishing and quiet weekend villas.",
    },
    {
        "name": "Playa Boca de Yuma",
        "province": "La Altagracia",
        "region": REGION_SOUTH,
        "latitude": 18.3680,
        "longitude": -68.6150,
        "access_type": "Public",
        "access_description": "Fishing town at the edge of Cotubanamá NP, southeast coast.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Local", "Eco", "Fishing"],
        "activities": ["Fishing", "Boating", "Photography"],
        "wildlife": ["Sea Birds", "Reef Fish"],
        "ecosystem": "Cliff coast at Cotubanamá National Park edge",
        "protected_area": True,
        "facilities": ["Seafood Restaurants", "Boat Trips"],
        "water_conditions": "Rugged coast; calmer river mouth",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Rugged fishing town beside Cotubanamá NP, famous for sport fishing and cave excursions.",
    },
    # ------------------------------------------ Southwest / Barahona (expansion)
    {
        "name": "Playa San Rafael",
        "province": "Barahona",
        "region": REGION_SOUTHWEST,
        "latitude": 18.0500,
        "longitude": -71.1000,
        "access_type": "Public",
        "access_description": "Coastal road south of Barahona city.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Scenic", "Eco", "Swimming"],
        "activities": ["Swimming", "Photography", "Hiking"],
        "wildlife": ["Crabs", "Sea Birds", "Reef Fish"],
        "ecosystem": "Mountain river meeting the Caribbean",
        "protected_area": False,
        "facilities": ["Natural Pools", "Food Stands"],
        "water_conditions": "Cool river pools beside the surf",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Iconic Barahona beach where a cold mountain river forms natural pools beside the sea.",
    },
    {
        "name": "Playa Los Patos",
        "province": "Barahona",
        "region": REGION_SOUTHWEST,
        "latitude": 18.0200,
        "longitude": -71.1800,
        "access_type": "Public",
        "access_description": "Roadside on the Barahona–Paraíso coastal highway.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Scenic", "Family", "Swimming"],
        "activities": ["Swimming", "Photography"],
        "wildlife": ["Sea Birds", "Fish"],
        "ecosystem": "Pebble beach with a freshwater lagoon",
        "protected_area": False,
        "facilities": ["Food Stands", "Natural Lagoon"],
        "water_conditions": "Calm lagoon beside Caribbean surf",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Pebbly Barahona beach famed for the world's shortest river and a calm swimming lagoon.",
    },
    {
        "name": "Playa Quemaíto",
        "province": "Barahona",
        "region": REGION_SOUTHWEST,
        "latitude": 18.1300,
        "longitude": -71.1000,
        "access_type": "Public",
        "access_description": "Short track off the coastal road south of Barahona.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Quiet", "Scenic", "Swimming"],
        "activities": ["Swimming", "Snorkeling", "Photography"],
        "wildlife": ["Reef Fish", "Crabs"],
        "ecosystem": "Pebble-and-sand cove with clear water",
        "protected_area": False,
        "facilities": ["Small Guesthouses"],
        "water_conditions": "Clear, deepening quickly",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Peaceful Barahona cove with exceptionally clear water and a tranquil, scenic setting.",
    },
    {
        "name": "Playa Saladilla",
        "province": "Barahona",
        "region": REGION_SOUTHWEST,
        "latitude": 18.1700,
        "longitude": -71.1050,
        "access_type": "Public",
        "access_description": "North of Barahona city along the coastal road.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Family", "Swimming"],
        "activities": ["Swimming", "Fishing"],
        "wildlife": ["Pelicans", "Fish"],
        "ecosystem": "Long open Caribbean beach",
        "protected_area": False,
        "facilities": ["Local Restaurants"],
        "water_conditions": "Gentle Caribbean waves",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Broad, family-friendly Barahona beach with calm water and local seafood spots.",
    },
    {
        "name": "Playa Juan de Bolaños",
        "province": "Monte Cristi",
        "region": REGION_NORTH,
        "latitude": 19.8700,
        "longitude": -71.6500,
        "access_type": "Public",
        "access_description": "Main beach of Monte Cristi in the far northwest.",
        "entrance_fee": "Free",
        "parking": True,
        "beach_type": ["Local", "Eco", "Swimming"],
        "activities": ["Swimming", "Boating", "Birdwatching"],
        "wildlife": ["Flamingos", "Sea Birds", "Reef Fish"],
        "ecosystem": "Gateway to El Morro National Park",
        "protected_area": True,
        "facilities": ["Hotels", "Restaurants", "Boat Tours"],
        "water_conditions": "Calm bay water",
        "best_time_to_visit": "December–April (dry season)",
        "description": "Monte Cristi's main beach and base for El Morro National Park and Cayos Siete Hermanos tours.",
    },
]


def beaches_with_maps() -> list[dict]:
    """Return BEACHES with a derived google_maps_url field added to each."""
    enriched = []
    for b in BEACHES:
        item = dict(b)
        item["google_maps_url"] = google_maps_url(b["latitude"], b["longitude"])
        enriched.append(item)
    return enriched


def all_provinces() -> list[str]:
    return sorted({b["province"] for b in BEACHES})


def all_activities() -> list[str]:
    acts: set[str] = set()
    for b in BEACHES:
        acts.update(b["activities"])
    return sorted(acts)


def all_regions() -> list[str]:
    # Preserve a sensible geographic order rather than alphabetical.
    order = [REGION_EAST, REGION_NORTH, REGION_SAMANA, REGION_SOUTH, REGION_SOUTHWEST]
    present = {b["region"] for b in BEACHES}
    return [r for r in order if r in present]
